# 洛晴的个人网站配置
title: 洛晴的小站
SEOTitle: 洛晴 | 前端开发者 & 插画爱好者
header-img: img/moonlight-bg.jpg  # 改用月光主题背景图
email: luoqing@example.com
description: "这里是洛晴的创意空间，分享前端开发心得和数字插画作品 | 在代码与画笔间寻找平衡"
keyword: "洛晴, 前端开发, JavaScript, Vue, 数字插画, 个人博客, 技术博客"
url: "https://luoqing.me"
baseurl: ""

# 功能设置
future: true
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["node_modules", "package.json"]

# 社交账号
github_username: luoqing
twitter_username: luoqing_art
instagram_username: luoqing_doodles
pixiv_username: luoqing

# 评论系统
disqus_username: luoqing-blog

# 分析统计
ga_track_id: "UA-XXXXXX-XX"
ga_domain: luoqing.me

# 侧边栏
sidebar: true
sidebar-about-description: "昼码代码，夜执画笔<br>Vue爱好者 | 插画练习生"
sidebar-avatar: https://github.com/luoqing.png

# 特色标签
featured-tags: true
featured-condition-size: 2

# 视觉主题
theme-color: "#5e35b1"  # 深紫色主题

# 特色功能
service-worker: true
canvas-nest: true  # 添加背景动画效果

# 友链
friends:
  [
    { title: "星辰阁", href: "https://xingchen.ge" },
    { title: "萤火小筑", href: "https://firefly.me" },
    { title: "代码绘", href: "https://code-paint.art" },
    { title: "Vue社区", href: "https://vue-community.org" },
  ]

# 作品集展示
portfolio:
  enable: true
  items:
    [
      { title: "Vue组件库", img: "img/works/vue-components.png", url: "#" },
      { title: "星空插画集", img: "img/works/stars-collection.jpg", url: "#" }
    ]
